<?php declare(strict_types=1);
namespace SwagShopFinder\Core\Content\ShopFinder\Aggregate\ShopFinderTranslation;
use Shopware\Core\Framework\DataAbstractionLayer\EntityTranslationDefinition;
use Shopware\Core\Framework\DataAbstractionLayer\FieldCollection;

class ShopFinderTranslationDefinition extends EntityTranslationDefinition
{
    public const ENTITY_NAME="swag_shop_finder_translation";
    public function getEntityName(): string
    {
        return self::ENTITY_NAME;
    }
    public function getEntityClass(): string
    {
        return parent::getEntityClass(); // TODO: Change the autogenerated stub
    }
    public function getCollectionClass(): string
    {
        return parent::getCollectionClass(); // TODO: Change the autogenerated stub
    }
    public function getParentDefinitionClass(): string
    {
        return parent::getParentDefinitionClass(); // TODO: Change the autogenerated stub
    }

    protected function defineFields(): FieldCollection
    {
        return new FieldCollection();
        // TODO: Implement defineFields() method.
    }
}

